### ISSUE TITLE
TaskList 语法尝试-test

### ISSUE THREAD

**Issue by ifengkou** [ifengkou/webpack-avalon#2]
# 本月计划的任务
- [ ] 完成ES6语法改造
- [ ] 完成非正常单词改造
- [x]  学完GITHUB特殊技巧

**Comment by ifengkou** [comment]
:100:

**Comment by ifengkou** [comment]
想引用这里的评论时
只要选中后按R键便会自动以引用的形式添加到评论栏

**Comment by ifengkou** [comment]
> 只要选中后按R键便会自动以引用的形式添加到评论栏

It`s true!!

**Comment by ifengkou** [comment]
fix #2

**Comment by Mrs-Code** [comment]
我想问下 怎么才能判断 模块js 里头是否require了 vendor 集合里头的js 因为我想如果没有因用 vendor 里头的 就不插入到 html里头。

**Comment by Mrs-Code** [comment]
就是判断 模块中是否引用了公用库 “vendor”中的脚本，如果没有 则不注入到html 里头，这个要怎么实现？
