### ISSUE TITLE
测试环境编译时，漏了一个css文件

### ISSUE THREAD

**Issue by johnsoncheg** [ifengkou/webpack-avalon#3]
index.css样式中设置了背景图片，但index没有被编译到build文件中去，并且我想问一下images为什么也没被build

**Comment by ifengkou** [comment]
是按照 `入口js文件` 按需加载资源的，如果index.css 没有被require，那么它就不会被编译到dist 目录中去。image除了在css中用，也可以直接在js里面require('image.png')，这样图片就会被打包编译。不知道我这样理解对不 :smile:

**Comment by johnsoncheg** [comment]
前面找到解决办法了，把img loaders里一句 'image?{bypassOnDebug:true, progressive:true,optimizationLevel:3,pngquant:{quality:"65-80",speed:4}}'注释掉就正常了

**Comment by ifengkou** [comment]
这个不需要注释，你 pull  下 `package.json` 这个文件，里面有个image-webpack-loader 忘了加上了

**Comment by ifengkou** [comment]
`image?{bypassOnDebug:true, progressive:true,optimizationLevel:3,pngquant:{quality:"65-80",speed:4}}`
是用来压缩大图片的。 具体可以参看https://github.com/tcoopman/image-webpack-loader

**Comment by johnsoncheg** [comment]
好的
